# Generated by Django 5.1.14 on 2026-05-13 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "station_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("station_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "train_no",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("train_name", models.CharField(max_length=100)),
                (
                    "destination_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destination_trains",
                        to="railways.station",
                    ),
                ),
                (
                    "source_station",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_trains",
                        to="railways.station",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainRunningDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MON", "Monday"),
                            ("TUE", "Tuesday"),
                            ("WED", "Wednesday"),
                            ("THU", "Thursday"),
                            ("FRI", "Friday"),
                            ("SAT", "Saturday"),
                            ("SUN", "Sunday"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="running_days",
                        to="railways.train",
                    ),
                ),
            ],
            options={
                "unique_together": {("train", "day_of_week")},
            },
        ),
        migrations.CreateModel(
            name="TrainSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stop_sequence", models.IntegerField()),
                ("arrival_time", models.TimeField(blank=True, null=True)),
                ("departure_time", models.TimeField(blank=True, null=True)),
                ("distance", models.IntegerField(default=0)),
                ("day_count", models.IntegerField(default=0)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="railways.station",
                    ),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="railways.train",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["station"], name="railways_tr_station_885435_idx"
                    )
                ],
                "unique_together": {("train", "stop_sequence")},
            },
        ),
    ]
